apiVersion: v1
kind: Service
metadata:
  name: my-first-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: my-first-deployment
  sessionAffinity: None
  type: LoadBalancer
